/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.divotek.callback;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author maxxl
 */
public class Main extends javax.swing.JFrame {
private static volatile Main instance;
	
public static Main getInstanceMain() throws ClassNotFoundException, java.text.ParseException
   {
	if(instance == null)
	{
	   synchronized (Main.class)
	   {
		if(instance == null)
		{
		   instance = new Main();
		}
		System.out.println("Create new Instanse Main");
	   }
	}
	System.out.println("Return Instanse Main");

	return instance;
   }


    /** Creates new form NewJFrame */
    public Main() {
        initComponents();
	   
	   
	   new Thread (
	   
			()->
			{
			 try
   {
	ServerSocket ss = new ServerSocket(6662);
  
        while (true) {
            Socket s = ss.accept();
            System.err.println("Client accepted");
            new Thread(new HttpServer.SocketProcessor(s)).start();
        }
   }
   catch (IOException ex)
   {
	Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
   }
   catch (Throwable ex)
   {
	Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
   }
			
			}
	   ).start();
  
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jScrollPane2 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList();
      jButton1 = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(255, 255, 255));

      jScrollPane2.setViewportView(jList1);

      jButton1.setText("Позвонить");
      jButton1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jButton1ActionPerformed(evt);
         }
      });

      jLabel1.setText("Список номеров которым нужно позвонить");

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
               .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                  .add(0, 0, Short.MAX_VALUE)
                  .add(jButton1))
               .add(layout.createSequentialGroup()
                  .add(jLabel1)
                  .add(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(8, 8, 8)
            .add(jLabel1)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 222, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
            .add(jButton1)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
   {//GEN-HEADEREND:event_jButton1ActionPerformed

ToForm ist = ToForm.getInstance();
DefaultListModel mod = ist.GetListModel();
Object get = mod.get(jList1.getSelectedIndex());
if(!get.toString().contains("Позвонил"))
{
get+=" Позвонил";
}
else
{
   JOptionPane.showMessageDialog(null,"Вы уже звонили на этот номер.");
}
mod.setElementAt(get, jList1.getSelectedIndex());
jList1.setModel(mod);

// TODO add your handling code here:
   }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
	  {
	     try
	     {
		  getInstanceMain().setVisible(true);
	     }
	     catch (ClassNotFoundException | ParseException ex)
	     {
		  Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	     }
	  });
	  /* Сюда писать код */
	  
	  
	  
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JList jList1;
   private javax.swing.JScrollPane jScrollPane2;
   // End of variables declaration//GEN-END:variables
   public JList getjList1()
   {
	return jList1;
   }
   public void setjList1(JList jList1)
   {
	this.jList1 = jList1;
   }
   
  

}
